const colorEyes = '#800000';
let user ;
let userName = 'Karina';
user = userName;
console.log (user);
let myColorEyes ;
myColorEyes = colorEyes;
console.log (myColorEyes);
console.log ('20' + '22');
console.log (20 +22);
console.log (typeof colorEyes);
let age;
console.log (typeof age);